### ISSUE TITLE
Remove "official" from readme and blurb/description?

### ISSUE THREAD

**Issue by phoenixy1** [burstware/expo-plaid-link#14]
Hi,

I'm from the Plaid team and we wanted to say thanks for supporting the Plaid ecosystem! We do have a request -- would you be willing to remove the word "official" from the readme and the description of this project on GitHub / npm? ("Use the official Plaid Link flow inside your expo app.") We think that it might make some developers think this is a Plaid supported package rather than a community supported package.

P.S. We'd love to send you some swag for your contributions -- if you'd like some, please email me your address and t-shirt size at ahoffer@plaid.com.

**Comment by JBaczuk** [comment]
Hi @phoenixy1 I can see how that might be confusing, I'll change that!
