### ISSUE TITLE
Broken demo app

### ISSUE THREAD

**Issue by pjelar** [burstware/expo-plaid-link#2]
I've tried the demo app but no luck. It launches but nothing shows up on screen.

Any ideas?

**Comment by JBaczuk** [comment]
@pjelar Did you use a real token?

**Comment by pjelar** [comment]
Using a sandbox token. Do I need a real token?

**Comment by JBaczuk** [comment]
@pjelar No, that should be fine. I will look into it, have you tried importing the module into it's own project?

**Comment by JBaczuk** [comment]
@pjelar In order to launch the demo app, you have to change the `"main"` entry in the `package.json` to `"main": "node_modules/expo/AppEntry.js",`. I'll update the README.

**Comment by pjelar** [comment]
Thanks for updating
